apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: https://chartmuseum.12ab.pw/
    #chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: 12prod
    devEnvApprovers:
    - todo
    environmentGitOwner: aeggerd
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
  - key: staging
  - key: production
  ingress:
    domain: "analy.sbs"
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
